# Generated by Django 5.0.3 on 2024-04-20 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_booking_options_remove_booking_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='account.booking'),
            preserve_default=False,
        ),
    ]
