# Generated by Django 5.0.3 on 2024-04-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_train_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
