# Generated by Django 5.0.3 on 2024-04-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_class_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'classes'},
        ),
        migrations.AlterField(
            model_name='train',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
